//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AAVM_EOL_Program.rc
//
#define IDD_DIALOG_MAIN                 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SET                  129
#define IDD_EXPRESS_IMG_DIALOG          134
#define IDD_Front_Image                 138
#define IDD_Rear_Image                  139
#define IDD_Left_Image                  140
#define IDD_Right_Image                 141
#define IDC_EDIT_SYS_STATUS             1001
#define IDC_EDIT_SPD_EXCEED             1002
#define IDC_EDIT_WIPER_STATUS           1003
#define IDC_EDIT_TURN_L                 1004
#define IDC_EDIT_TURN_R                 1005
#define IDC_EDIT_RECOGNIZE_L            1006
#define IDC_EDIT_RECOGNIZE_R            1007
#define IDC_EDIT_WARNING_L              1008
#define IDC_EDIT_COM_IOBOARD_1          1008
#define IDC_EDIT_WARNING_R              1009
#define IDC_EDIT_WARNING_HAP            1010
#define IDC_EDIT_HBA_SYS_STATUS         1014
#define IDC_EDIT_HBA_LAMP_OFF           1015
#define IDC_EDIT_CAN_LDWS               1016
#define IDC_EDIT_CAN_FLI2               1016
#define IDC_EDIT_IN_TURN_L              1017
#define IDC_EDIT_IN_TURN_R              1018
#define IDC_EDIT_IN_HEAD_LAMP_LOW       1019
#define IDC_EDIT_IN_HEAD_LAMP_HIGH      1020
#define IDC_EDIT_IN_WIPER_LOW           1021
#define IDC_EDIT_IN_WIPER_HIGH          1022
#define IDC_EDIT_IN_VEHICLE_SPEED       1023
#define IDC_EDIT_IN_LDWS_SW             1024
#define IDC_EDIT_FILENAME_LOG_1         1024
#define IDC_EDIT_IN_HEAD_LAMP_HIGH_SW   1025
#define IDC_EDIT_IO_OUT_BARCODE_1       1025
#define IDC_EDIT_IN_LIGHT_SW_STATUS     1026
#define IDC_EDIT_CAN_CLU1               1027
#define IDC_EDIT_CAN_CMMSG02            1027
#define IDC_EDIT_CAN_CLU2               1028
#define IDC_EDIT_CAN_IPSMMSG02          1028
#define IDC_EDIT_BF_BOOT_VER            1028
#define IDC_EDIT_CAN_GATEWAY2           1029
#define IDC_EDIT_CAN_XBR                1029
#define IDC_EDIT_IO_OUT_BARCODE_2       1029
#define IDC_BTN_SET                     1030
#define IDC_EDIT_TEST_NUM_OK            1031
#define IDC_EDIT_BF_VER_ARG             1031
#define IDC_EDIT_TEST_NUM_ALL           1032
#define IDC_EDIT_CAN_TCU1               1033
#define IDC_EDIT_CAN_DM1                1033
#define IDC_LIST_PROCESS                1034
#define IDC_EDIT_TEST_NUM_RATE          1035
#define IDC_EDIT_COM_BARCODE1           1036
#define IDC_EDIT_CARNAME                1036
#define IDC_EDIT_TEST_EMERALD_L         1036
#define IDC_EDIT_COM_BARCODE2           1037
#define IDC_EDIT_CAN_CMMSG01            1037
#define IDC_EDIT_COM_IOBOARD            1038
#define IDC_EDIT_CAN_FLI1               1038
#define IDC_EDIT_COM_Emerald            1038
#define IDC_EDIT_COM_SCREW              1039
#define IDC_EDIT_IN_HARZARD             1039
#define IDC_EDIT_IN_GEAR_TYPE           1040
#define IDC_EDIT_COM_AMMETER            1040
#define IDC_EDIT_COM_BF609              1040
#define IDC_EDIT_TESTER_LINE            1041
#define IDC_EDIT_TEST_BF609             1041
#define IDC_EDIT_TESTER_NAME            1042
#define IDC_BTN_FILENAME_LOG            1043
#define IDC_EDIT_OUT_HARZARD            1043
#define IDC_EDIT_MONITOR                1044
#define IDC_EDIT_COM_BARCODE_1          1044
#define IDC_EDIT_IO_OUT_BARCODE1        1046
#define IDC_EDIT_COM_BARCODE_2          1046
#define IDC_EDIT_IO_OUT_BARCODE2        1047
#define IDC_EDIT_COM_AMMETER2           1047
#define IDC_EDIT_IO_OUT_POWER           1048
#define IDC_EDIT_IO_IN_CONNECT          1049
#define IDC_EDIT_FILENAME_LOG           1050
#define IDC_BTN_MONITOR                 1051
#define IDC_EDIT_IO_IN_12V_OVER         1052
#define IDC_BTN_TEST                    1052
#define IDC_BTN_START                   1052
#define IDC_EDIT_ECU_ID                 1053
#define IDC_EDIT_IO_IN_12V_UNDER        1054
#define IDC_COMBO_CAR_TYPE              1055
#define IDC_COMBO_LOCATION              1056
#define IDC_BTN_SET_TEST                1057
#define IDC_CHECK_IO_IN_CONNECT         1058
#define IDC_CHECK_IO_IN_12V_OVER        1059
#define IDC_CHECK_IO_IN_12V_UNDER       1060
#define IDC_EDIT_IO_IN_24V_OVER         1061
#define IDC_EDIT_IO_IN_AMPERE_OVER_24   1061
#define IDC_CHECK_IO_IN_24V_OVER        1062
#define IDC_EDIT_IO_IN_24V_UNDER        1063
#define IDC_EDIT_IO_IN_AMPERE_UNDER_24  1063
#define IDC_EDIT_IO_IN_CANLINE          1064
#define IDC_CHECK_IO_OUT_BARCODE1       1065
#define IDC_CHECK_IO_OUT_BARCODE2       1066
#define IDC_CHECK_IO_OUT_POWER          1067
#define IDC_EDIT_IO_OUT_DISCONECT       1068
#define IDC_CHECK_IO_OUT_DISCONNECT     1069
#define IDC_EDIT_IO_OUT_LED_Y           1070
#define IDC_CHECK_IO_OUT_LED_Y          1071
#define IDC_EDIT_IO_OUT_LED_G           1072
#define IDC_CHECK_IO_OUT_LED_G          1073
#define IDC_EDIT_IO_OUT_LED_R           1074
#define IDC_CHECK_IO_OUT_LED_R          1075
#define IDC_EDIT_TESTER_TIME            1076
#define IDC_EDIT_TEST_BARCODE1          1076
#define IDC_BTN_READY                   1077
#define IDC_TXT_GUIDE                   1078
#define IDC_EDIT_IO_OUT_LDWS_BTN        1079
#define IDC_TXT_LABEL                   1079
#define IDC_CHECK_IO_OUT_LDWS_BTN       1080
#define IDC_EDIT_TEST_BARCODE2          1081
#define IDC_EDIT_TEST_SCREW             1082
#define IDC_EDIT_TEST_IOBOARD           1083
#define IDC_CHECK_IO_IN_24V_UNDER       1084
#define IDC_EDIT_ECU_VER_BOOT           1085
#define IDC_EDIT_ECU_VER_SW             1086
#define IDC_EDIT_ECU_VER_HW             1087
#define IDC_BTN_MAUAL_ERROR             1088
#define IDC_CHECK_IO_IN_CANLINE         1088
#define IDC_COMBO_TESTER_LINE           1089
#define IDC_EDIT_TEST_AMMETER           1089
#define IDC_COMBO_TESTER_NAME           1090
#define IDC_EDIT_IO_IN_AMPERE_OVER      1090
#define IDC_EDIT_IO_IN_AMPERE_OVER_12   1090
#define IDC_EDIT_PIN_USED               1091
#define IDC_EDIT_IO_IN_AMPERE_UNDER     1091
#define IDC_EDIT_IO_IN_AMPERE_UNDER_12  1091
#define IDC_EDIT_IN_FRONT_GROG          1092
#define IDC_EDIT_CAN_CLU3               1093
#define IDC_EDIT_CAN_GATEWAY6           1093
#define IDC_EDIT_CAN_MFSMMSG02          1093
#define IDC_COMBO_PROGRAM_TYPE          1094
#define IDC_COMBO_TIME_DELAY            1095
#define IDC_EDIT_CAN_CCVS               1095
#define IDC_COMBO_PROGRAM_TYPE2         1095
#define IDC_COMBO_VOLTAGE               1095
#define IDC_EDIT_BOX_UNIT_MAX           1096
#define IDC_EDIT_BOX_UNIT_CNT           1097
#define IDC_SPIN_BOX_UNIT_CNT           1099
#define IDC_STATIC_LINE_NAME            1100
#define IDC_BUTTON1                     1102
#define IDC_BUTTON2                     1103
#define IDC_CHECK_MODE_NIGHT            1106
#define IDC_EDIT_CAMERA_STAT_FRONT      1107
#define IDC_EDIT_CAMERA_STAT_RIGHT      1108
#define IDC_EDIT_BARCODE_PCB            1109
#define IDC_EDIT_BARCODE_CASE           1110
#define IDC_EDIT3                       1111
#define IDC_EDIT_BARCODE_CASE2          1111
#define IDC_CHECK_MODE_WIPER            1112
#define IDC_EDIT_EMERALD_STAT           1113
#define IDC_EDIT_BF609_STAT             1114
#define IDC_EDIT_BF609_FPS              1115
#define IDC_EDIT_CAMERA_STAT_REAR       1116
#define IDC_EDIT_CAMERA_STAT_LEFT       1117
#define IDC_EDIT_CAMERA_GAIN_FRONT      1118
#define IDC_EDIT_CAMERA_GAIN_RIGHT      1119
#define IDC_EDIT_CAMERA_GAIN_REAR       1120
#define IDC_EDIT_CAMERA_GAIN_LEFT       1121
#define IDC_CHECK_MODE_INTWIPER         1122
#define IDC_CHECK_MODE_MOVE             1123
#define IDC_CHECK_MODE_SWING            1124
#define IDC_EDIT_AAVM_VIEW_MODE         1125
#define IDC_CHECK4                      1126
#define IDC_CHECK_MODE_WORK             1126
#define IDC_EDIT_AAVM_IMOD_STATUS       1127
#define IDC_EDIT_AAVM_MODEL_STATUS      1128
#define IDC_EDIT_AAVM_WARNING_FRONT     1129
#define IDC_EDIT_AAVM_DTC               1130
#define IDC_EDIT_AAVM_WARNING_REAR      1131
#define IDC_EDIT_CAN_AAVO               1132
#define IDC_EDIT_AAVM_WARNING_LEFT      1133
#define IDC_CHECK_MODE_INTWIPER2        1134
#define IDC_CHECK_MODE_MANUAL_OFF       1134
#define IDC_EDIT_AAVM_WARNING_RIGHT     1135
#define IDC_EDIT_HP2_TRAVEL             1140
#define IDC_EDIT_MMS_MOVE               1140
#define IDC_EDIT_CAN_HP2                1141
#define IDC_EDIT_HP3_SWING              1142
#define IDC_EDIT_HP2_WORK               1143
#define IDC_EDIT_HP3_BOOM_UP            1143
#define IDC_EDIT_CAN_HP3                1144
#define IDC_EDIT_HP3_BOOM_DN            1144
#define IDC_EDIT_HP1_ARM                1145
#define IDC_EDIT_ESROS_WIPER            1146
#define IDC_EDIT_ESROS_INTWIPER         1147

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
